'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var STUDENTS_FETCH_START = exports.STUDENTS_FETCH_START = Symbol('STUDENTS_FETCH_START');
var STUDENTS_FETCH_SUCCESS = exports.STUDENTS_FETCH_SUCCESS = Symbol('STUDENTS_FETCH_SUCCESS');
var STUDENTS_FETCH_FAILURE = exports.STUDENTS_FETCH_FAILURE = Symbol('STUDENTS_FETCH_FAILURE');

var FILTER_STUDENTS_START = exports.FILTER_STUDENTS_START = Symbol('FILTER_STUDENTS_START');
var FILTER_STUDENTS_SUCCESS = exports.FILTER_STUDENTS_SUCCESS = Symbol('FILTER_STUDENTS_SUCCESS');

var SORT_STUDENTS_START = exports.SORT_STUDENTS_START = Symbol('SORT_STUDENTS_START');
var SORT_STUDENTS_SUCCESS = exports.SORT_STUDENTS_SUCCESS = Symbol('SORT_STUDENTS_SUCCESS');

var STUDENTDATA_FETCH_START = exports.STUDENTDATA_FETCH_START = Symbol('STUDENTDATA_FETCH_START');
var STUDENTDATA_FETCH_SUCCESS = exports.STUDENTDATA_FETCH_SUCCESS = Symbol('STUDENTDATA_FETCH_SUCCESS');
var STUDENTDATA_FETCH_FAILURE = exports.STUDENTDATA_FETCH_FAILURE = Symbol('STUDENTDATA_FETCH_FAILURE');

var START_GET_Q = exports.START_GET_Q = Symbol('START_GET_Q');
var SUCCESS_GET_Q = exports.SUCCESS_GET_Q = Symbol('SUCCESS_GET_Q');
var FAIL_GET_Q = exports.FAIL_GET_Q = Symbol('FAIL_GET_Q');

var SEND_START = exports.SEND_START = Symbol('SEND_START');
var SEND_SUCCESS = exports.SEND_SUCCESS = Symbol('SEND_SUCCESS');
var SEND_FAIL = exports.SEND_FAIL = Symbol('SEND_FAIL');

var START_LOGIN = exports.START_LOGIN = Symbol('START_LOGIN');
var SUCCESS_LOGIN = exports.SUCCESS_LOGIN = Symbol('SUCCESS_LOGIN');
var FAILURE_LOGIN = exports.FAILURE_LOGIN = Symbol('FAILURE_LOGIN');

var STORE_ANSWER = exports.STORE_ANSWER = Symbol(' STORE_ANSWER');
var STORE_DATA_FAILURE = exports.STORE_DATA_FAILURE = Symbol(' STORE_DATA_FAILURE');
var STORE_DATA_SUCCESS = exports.STORE_DATA_SUCCESS = Symbol(' STORE_DATA_SUCCESS');

var SUCCESS_GET_USERID = exports.SUCCESS_GET_USERID = Symbol('SUCCESS_GET_USERID');
var FAILURE_GET_USERID = exports.FAILURE_GET_USERID = Symbol('FAILURE_GET_USERID');

var START_SETTINGS = exports.START_SETTINGS = Symbol('START_SETTINGS');
var SUCCESS_SETTINGS = exports.SUCCESS_SETTINGS = Symbol('SUCCESS_SETTINGS');
var FAILURE_SETTINGS = exports.FAILURE_SETTINGS = Symbol('FAILURE_SETTINGS');

var UPDATE_DATA_USER = exports.UPDATE_DATA_USER = Symbol('UPDATE_DATA_USER');
var FAILURE_UPDATE = exports.FAILURE_UPDATE = Symbol('FAILURE_UPDATE');

var SUCCESS_GET_NEW_USER = exports.SUCCESS_GET_NEW_USER = Symbol('SUCCESS_GET_NEW_USER');